### ISSUE TITLE
This does not play well with github pages

### ISSUE THREAD

**Issue by edap** [BorisMoore/jsrender#321] opened 2017-05-18 10:16 UTC
The syntax `{{}}` is the same adopted by the liquid template engine used on github pages. As consequence, the template is interpreted.

**Comment by BorisMoore** [comment] 2017-05-18 16:52
This is a duplicate of https://github.com/BorisMoore/jsrender/issues/281.

You can use `$.views.settings.delimiters(...)` (http://www.jsviews.com/#settings/delimiters) to set different delimiters.

**Closed by BorisMoore** 2017-05-18 16:52 UTC
